name: Purge All Cloudflare Cache

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  purge-all:
    runs-on: ubuntu-latest

    steps:
      - name: Purge all Cloudflare cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{
              "purge_everything": true
            }'
